### ISSUE TITLE
Extend README with install information

### ISSUE THREAD

**Issue by zuphilip** [quadflor/Quadflor#1]
It seems that the information about installing is currently missing in the README. I found some information in your documentation and tried to extend the README: https://github.com/zuphilip/Quadflor/tree/extend-readme but I haven't tried it out yet. Moreover, I fixed a typo in the usage section.

**Comment by lgalke** [comment]
Thanks Philip :+1:, the README itself will be extended during the next days. I will also include your installation instructions.
